apiVersion: v1
kind: Pod
metadata:
  name: unpriv-ubuntu
spec:
  containers:
    - image: unpriv-ubuntu:latest
      name: unpriv-ubuntu
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"